export const STORE_TYPE = {
    ALL_PAGINATION_DATA: 'allPaginationsData',
    CURRENT_PAGE_DATA: 'currentPageData',
    TOTAL: 'total',
    LOAD_CURRENT_PAGE_DATA: 'loadCurrentPageData',
    CURRENT_PAGE: 'currentPage',
    SHOW_HIDE_LOADER: 'showHideLoader',
    TOASTER_ERROR: 'toaster/error',
    TOASTER_SUCCESS: 'toaster/success',
    TOASTER_INFO: 'toaster/info',
    TOASTER_WARNING: 'toaster/warning',
    TOASTER_CLEAR: 'toaster/clear',
    CLEAR: 'clear',
    LOGIN: 'login',
    LOGOUT: 'logout',
    PROFILE: 'profile',
    REGISTER: 'register',
    ADD_EMPLOYEE: 'addEmployee',
    EDIT_EMPLOYEE: 'editEmployee',
    SET_CURRENT_URL: 'setCurrentURL',
    SET_IS_RESTE_STATE: 'setIsResetState',
    SELECTED_EMPLOYEE: 'selectedEmployee',
    UPDATE_CURRENT_PAGE_DATA: 'updateCurrentPageData',
    DELETE_EMPLOYEE: 'deleteEmployee',
    COMMAN_SHOW_HIDE_LOADER: 'comman/showHideLoader',

    MESSAGE: 'message',
    TYPE: 'type',
    CURRENT_URL: 'currentUrl',
    IS_RESET_STATE: 'isResetState',
    EMPLOYEE: 'employee',
    SHOW_LOADER: 'showLoader',
};

export const CONSTANT = {
    EMPLOYEES: 'employees',
    USER: 'user',
    FIRST_NAME: 'firstName',
    LAST_NAME: 'lastName',
    USERNANE: 'username',
    EMAIL: 'email',
    PASSWORD: 'password',
    CONFIRM_PASSWORD: 'confirmPassword',
    EMPLOYEE_AGE: 'employee_age',
    EMPLOYEE_SALARY: 'employee_salary',
    EMPLOYEE_NAME: 'employee_name',
    EMPLOYEE_ID: 'employee_id',

    URL_HOME: '/home',
    URL_LOGIN: '/login',
    URL_ADD_EDIT: '/addEdit',
    URL_ADD_EMPLOYEE: '/addEmployee',
    URL_EMPLOYEE: '/employee',
    URL_BLANK: '/',
    SUCCESS: 'success',
    ERROR: 'error',
    INFO: 'info',
    WARNING: 'warning',
};
